// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe956Ghh8MyffpTKPJruriz5UxvCinYqU',
    appId: '1:365634184458:web:3a51cd73dda192160706f3',
    messagingSenderId: '365634184458',
    projectId: 'beatz-b51ed',
    authDomain: 'beatz-b51ed.firebaseapp.com',
    storageBucket: 'beatz-b51ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgoCY8otAFWqKbmJ6t0HAMgF9Ag_EqEv8',
    appId: '1:365634184458:android:64c5474740cebc4b0706f3',
    messagingSenderId: '365634184458',
    projectId: 'beatz-b51ed',
    storageBucket: 'beatz-b51ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwlBvRVGodRsh1vlRVUzTvZptAtVLZ0ac',
    appId: '1:365634184458:ios:ebd0743071736bf60706f3',
    messagingSenderId: '365634184458',
    projectId: 'beatz-b51ed',
    storageBucket: 'beatz-b51ed.appspot.com',
    iosClientId: '365634184458-g4q198rr350i1f1t5o72uf4h5ebblabh.apps.googleusercontent.com',
    iosBundleId: 'com.example.log',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwlBvRVGodRsh1vlRVUzTvZptAtVLZ0ac',
    appId: '1:365634184458:ios:19d5f223af2a94fa0706f3',
    messagingSenderId: '365634184458',
    projectId: 'beatz-b51ed',
    storageBucket: 'beatz-b51ed.appspot.com',
    iosClientId: '365634184458-rc81srpntcnimssi28pe2ab8dut7v8ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.log.RunnerTests',
  );
}
